// <auto-generated />
namespace todo_list.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class up3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up3));
        
        string IMigrationMetadata.Id
        {
            get { return "202209010629511_up3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
